name: BedBackBetter
description: $description
version: '${version}'

main: io.github.ganyuke.bedbackbetter.BedBackBetter
api-version: '${paper_api_version}'
load: POSTWORLD

authors: [ ganyuke ]
website: https://github.com/ganyuke/BedBackBetter
